//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace todoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class toDo
    {
        public int id { get; set; }
        public int priorityTypeId { get; set; }
        public System.DateTimeOffset remindMeDate { get; set; }
        public string toDoDesc { get; set; }
    
        public virtual priorityType priorityType { get; set; }
    }
}
