USE [master]
GO

/****** Object:  Database [CodeChallange]    Script Date: 7/8/2016 2:55:10 AM ******/
CREATE DATABASE [CodeChallange]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CodeChallange', FILENAME = N'C:\Users\lenCodeChallange\CodeChallange.mdf' , SIZE = 3136KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CodeChallange_log', FILENAME = N'C:\Users\lenCodeChallange\CodeChallange_log.ldf' , SIZE = 832KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [CodeChallange] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CodeChallange].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CodeChallange] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CodeChallange] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CodeChallange] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CodeChallange] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CodeChallange] SET ARITHABORT OFF 
GO

ALTER DATABASE [CodeChallange] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [CodeChallange] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CodeChallange] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CodeChallange] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CodeChallange] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CodeChallange] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CodeChallange] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CodeChallange] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CodeChallange] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CodeChallange] SET  ENABLE_BROKER 
GO

ALTER DATABASE [CodeChallange] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CodeChallange] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CodeChallange] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CodeChallange] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CodeChallange] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CodeChallange] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CodeChallange] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CodeChallange] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CodeChallange] SET  MULTI_USER 
GO

ALTER DATABASE [CodeChallange] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CodeChallange] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CodeChallange] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CodeChallange] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [CodeChallange] SET  READ_WRITE 
GO

